In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("food_ordering_behavior_dataset.csv")

In [3]:
df

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,discount_applied,delivery_fee,time_taken_to_order,rating_given,is_repeat_order,mood,hunger_level,company,rainy_weather
0,1,2698,35,Pune,Evening,Weekend,Chinese,Dinner,Premium,971,Yes,90,13,1,Yes,Celebrating,High,Partner,No
1,2,3237,44,Mumbai,Night,Weekend,South Indian,Dinner,Budget,442,No,26,13,2,No,Lazy,Low,Family,No
2,3,3626,31,Delhi,Morning,Weekend,Biryani,Breakfast,Mid-range,739,Yes,85,10,2,Yes,Happy,Medium,Friends,No
3,4,3176,23,Delhi,Evening,Weekend,Biryani,Snacks,Mid-range,466,No,44,12,2,No,Happy,Medium,Alone,No
4,5,4824,26,Chandigarh,Morning,Weekday,Chinese,Lunch,Premium,927,Yes,58,13,2,No,Happy,Medium,Partner,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,3569,40,Hyderabad,Afternoon,Weekday,North Indian,Lunch,Premium,734,Yes,87,6,5,No,Happy,High,Friends,Yes
49996,49997,1087,42,Chandigarh,Morning,Weekend,Fast Food,Lunch,Mid-range,764,Yes,24,14,5,No,Happy,Low,Alone,No
49997,49998,3645,35,Pune,Morning,Weekday,South Indian,Snacks,Budget,985,Yes,53,2,5,Yes,Lazy,Medium,Alone,Yes
49998,49999,3630,34,Delhi,Morning,Weekend,Desserts,Snacks,Premium,860,Yes,48,6,3,Yes,Happy,Low,Alone,Yes


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   order_id             50000 non-null  int64 
 1   user_id              50000 non-null  int64 
 2   age                  50000 non-null  int64 
 3   city                 50000 non-null  object
 4   order_time           50000 non-null  object
 5   day_type             50000 non-null  object
 6   cuisine              50000 non-null  object
 7   meal_type            50000 non-null  object
 8   restaurant_type      50000 non-null  object
 9   order_value          50000 non-null  int64 
 10  discount_applied     50000 non-null  object
 11  delivery_fee         50000 non-null  int64 
 12  time_taken_to_order  50000 non-null  int64 
 13  rating_given         50000 non-null  int64 
 14  is_repeat_order      50000 non-null  object
 15  mood                 50000 non-null  object
 16  hung

In [5]:
df.isna().sum()

order_id               0
user_id                0
age                    0
city                   0
order_time             0
day_type               0
cuisine                0
meal_type              0
restaurant_type        0
order_value            0
discount_applied       0
delivery_fee           0
time_taken_to_order    0
rating_given           0
is_repeat_order        0
mood                   0
hunger_level           0
company                0
rainy_weather          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   order_id             50000 non-null  int64 
 1   user_id              50000 non-null  int64 
 2   age                  50000 non-null  int64 
 3   city                 50000 non-null  object
 4   order_time           50000 non-null  object
 5   day_type             50000 non-null  object
 6   cuisine              50000 non-null  object
 7   meal_type            50000 non-null  object
 8   restaurant_type      50000 non-null  object
 9   order_value          50000 non-null  int64 
 10  discount_applied     50000 non-null  object
 11  delivery_fee         50000 non-null  int64 
 12  time_taken_to_order  50000 non-null  int64 
 13  rating_given         50000 non-null  int64 
 14  is_repeat_order      50000 non-null  object
 15  mood                 50000 non-null  object
 16  hung

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [11]:
x =  df.drop(["order_id","user_id","rainy_weather"],axis=1)
y = df["rainy_weather"]

In [12]:
category_cols = [
    "city",
    "order_time",
    "day_type",
    "cuisine",
    "meal_type",
    "restaurant_type",
    "discount_applied",
    "is_repeat_order",
    "mood",
    "hunger_level",
    "company"
]

In [14]:
x = pd.get_dummies(x,columns=category_cols,drop_first=True,dtype=int)

In [15]:
x

,age,order_value,delivery_fee,time_taken_to_order,rating_given,city_Chandigarh,city_Delhi,city_Hyderabad,city_Mumbai,city_Pune,...,discount_applied_Yes,is_repeat_order_Yes,mood_Happy,mood_Lazy,mood_Stressed,hunger_level_Low,hunger_level_Medium,company_Family,company_Friends,company_Partner
0,35,971,90,13,1,0,0,0,0,1,...,1,1,0,0,0,0,0,0,0,1
1,44,442,26,13,2,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
2,31,739,85,10,2,0,1,0,0,0,...,1,1,1,0,0,0,1,0,1,0
3,23,466,44,12,2,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
4,26,927,58,13,2,1,0,0,0,0,...,1,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,40,734,87,6,5,0,0,1,0,0,...,1,0,1,0,0,0,0,0,1,0
49996,42,764,24,14,5,1,0,0,0,0,...,1,0,1,0,0,1,0,0,0,0
49997,35,985,53,2,5,0,0,0,0,1,...,1,1,0,1,0,0,1,0,0,0
49998,34,860,48,6,3,0,1,0,0,0,...,1,1,1,0,0,1,0,0,0,0


In [16]:
y

0         No
1         No
2         No
3         No
4        Yes
        ... 
49995    Yes
49996     No
49997    Yes
49998    Yes
49999     No
Name: rainy_weather, Length: 50000, dtype: object

In [17]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.2, stratify = y, random_state = 42
)

In [20]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [23]:
def run_knn(k):
    print(f"\n---k = {k}--")

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(x_train_scaled,y_train)

    y_pred = model.predict(x_test_scaled)

    accuracy = accuracy_score(y_test,y_pred)*100
    print(f"accuracy : {accuracy:.2f}%")

    classification = classification_report(y_test,y_pred)
    print("classification_report:\n",classification)

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    df = pd.DataFrame({
        "Actual": y_test,
        "Prediction" : y_pred
    })
    print("\n Comparison Table..")
    print(df.head(10))

run_knn(5)
run_knn(3)
run_knn(7)
run_knn(10)
run_knn(11)
run_knn(13)
run_knn(15)
run_knn(17)
run_knn(20)


---k = 5--
accuracy : 50.10%
classification_report:
               precision    recall  f1-score   support

          No       0.50      0.50      0.50      5001
         Yes       0.50      0.50      0.50      4999

    accuracy                           0.50     10000
   macro avg       0.50      0.50      0.50     10000
weighted avg       0.50      0.50      0.50     10000

Confusion Matrix:
[[2498 2503]
 [2487 2512]]

 Comparison Table..
      Actual Prediction
32881     No         No
39838     No         No
40308    Yes        Yes
34269     No        Yes
13765     No        Yes
48142     No         No
49454     No         No
40939     No        Yes
47093     No         No
40908     No        Yes

---k = 3--
accuracy : 49.46%
classification_report:
               precision    recall  f1-score   support

          No       0.49      0.50      0.50      5001
         Yes       0.49      0.49      0.49      4999

    accuracy                           0.49     10000
   macro avg     

In [35]:
x =  df.drop(["order_id","user_id","is_repeat_order"],axis=1)
y = df["is_repeat_order"]

In [37]:
category_cols = [
    "city",
    "order_time",
    "day_type",
    "cuisine",
    "meal_type",
    "restaurant_type",
    "discount_applied",
    "rainy_weather",
    "mood",
    "hunger_level",
    "company"
]

In [40]:
x = pd.get_dummies(x,columns=category_cols,drop_first=True,dtype=int)

In [41]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.2, stratify = y, random_state = 42
)

In [42]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [43]:
def run_knn(k):
    print(f"\n---k = {k}--")

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(x_train_scaled,y_train)

    y_pred = model.predict(x_test_scaled)

    accuracy = accuracy_score(y_test,y_pred)*100
    print(f"accuracy : {accuracy:.2f}%")

    classification = classification_report(y_test,y_pred)
    print("classification_report:\n",classification)

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    df = pd.DataFrame({
        "Actual": y_test,
        "Prediction" : y_pred
    })
    print("\n Comparison Table..")
    print(df.head(10))

run_knn(5)
run_knn(3)
run_knn(7)
run_knn(10)
run_knn(11)
run_knn(13)
run_knn(15)
run_knn(17)
run_knn(20)


---k = 5--
accuracy : 49.54%
classification_report:
               precision    recall  f1-score   support

          No       0.50      0.50      0.50      5003
         Yes       0.50      0.49      0.49      4997

    accuracy                           0.50     10000
   macro avg       0.50      0.50      0.50     10000
weighted avg       0.50      0.50      0.50     10000

Confusion Matrix:
[[2496 2507]
 [2539 2458]]

 Comparison Table..
      Actual Prediction
38424     No        Yes
23322     No        Yes
43672    Yes        Yes
9151      No         No
30057     No         No
19852     No         No
28575     No         No
26999     No         No
22574     No         No
9869      No        Yes

---k = 3--
accuracy : 49.50%
classification_report:
               precision    recall  f1-score   support

          No       0.50      0.50      0.50      5003
         Yes       0.49      0.49      0.49      4997

    accuracy                           0.49     10000
   macro avg     

In [122]:
x =  df.drop(["order_id","user_id","hunger_level"],axis=1)
y = df["hunger_level"]

In [123]:
category_cols = [
    "city",
    "order_time",
    "day_type",
    "meal_type",
    "discount_applied",
    "rainy_weather",
    "company",
    "is_repeat_order",
    "cuisine",
    "mood",
    "restaurant_type"
]

In [124]:
x = pd.get_dummies(x,columns=category_cols,drop_first=True,dtype=int)

In [125]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.2, stratify = y, random_state = 42
)

In [126]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [127]:
def run_knn(k):
    print(f"\n---k = {k}--")

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(x_train_scaled,y_train)

    y_pred = model.predict(x_test_scaled)

    accuracy = accuracy_score(y_test,y_pred)*100
    print(f"accuracy : {accuracy:.2f}%")

    classification = classification_report(y_test,y_pred)
    print("classification_report:\n",classification)

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    df = pd.DataFrame({
        "Actual": y_test,
        "Prediction" : y_pred
    })
    print("\n Comparison Table..")
    print(df.head(10))

run_knn(5)
run_knn(3)
run_knn(7)
run_knn(10)
run_knn(11)
run_knn(13)
run_knn(15)
run_knn(17)
run_knn(20)


---k = 5--
accuracy : 33.90%
classification_report:
               precision    recall  f1-score   support

        High       0.34      0.46      0.39      3344
         Low       0.34      0.34      0.34      3339
      Medium       0.34      0.21      0.26      3317

    accuracy                           0.34     10000
   macro avg       0.34      0.34      0.33     10000
weighted avg       0.34      0.34      0.33     10000

Confusion Matrix:
[[1552 1106  686]
 [1504 1132  703]
 [1507 1104  706]]

 Comparison Table..
       Actual Prediction
19401     Low        Low
16648    High       High
29762     Low        Low
13389  Medium        Low
3497      Low       High
48397  Medium     Medium
4194     High     Medium
7280      Low        Low
47635    High     Medium
5107   Medium       High

---k = 3--
accuracy : 34.27%
classification_report:
               precision    recall  f1-score   support

        High       0.34      0.49      0.40      3344
         Low       0.35      0.27

### Final Model Selection

After comparing the KNN models for different target variables, the **Rainy Weather Prediction model** achieved the highest accuracy.

The best result was obtained using **K = 10**, with an accuracy of **50.70%**.

Therefore, among the tested models, **KNN with `rainy_weather` as the target variable and K = 10** is selected as the best-performing model.

**Final Model:** K-Nearest Neighbors (KNN)
**Target Variable:** `rainy_weather`
**Classification Type:** Binary Classification
**Optimal K:** 10
**Accuracy:** 50.70%